/**
 * AppContext: Language (ES/EN) + Theme (4 themes) unified context.
 * Usage: const { lang, t, theme, setTheme, themeColors } = useAppContext();
 */
import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

// ─── Types ────────────────────────────────────────────────────────────────────
export type Lang  = 'es' | 'en';
export type Theme = 'cyber' | 'aurora' | 'crimson' | 'nebula' | 'ocean' | 'gold' | 'midnight';

export interface ThemeColors {
  c1: string; c2: string; c3: string; c4: string; bg: string; name: string; label: string;
}

// ─── Translations ─────────────────────────────────────────────────────────────
const STRINGS = {
  es: {
    appTitle: 'NOVA MUSIC LAB',
    appSubtitle: 'El Universo Musical de Lirioth',
    user: 'Usuario',
    loadData: 'Cargar Datos',
    nav: {
      dashboard:   'Dashboard',
      eras:        'Eras Musicales',
      top:         'Top Histórico',
      personality: 'Personalidad',
      emotions:    'Mapa Emocional',
      obsessions:  'Obsesiones',
      cultural:    'ADN Cultural',
      inner:       'Mundo Interior',
      artist:      'Si fuera Artista',
      insights:    'Insights Ocultos',
      compare:     'Spotify vs Last.fm',
      statsPro:    'Stats Pro',
      achievements:'Logros',
      report:      'Ensayo Final',
      upload:      'Subir Archivos',
    },
    kpi: {
      totalPlays:    'Plays Totales',
      hours:         'Horas Escuchadas',
      artists:       'Artistas Únicos',
      activeDays:    'Días Activos',
      bestYear:      'Mejor Año',
      avgPerDay:     'Promedio / Día',
      nightRatio:    'Escucha Nocturna',
      peakHour:      'Hora Pico',
      uniqueTracks:  'Canciones Únicas',
      uniqueAlbums:  'Álbumes Únicos',
    },
    records: {
      title:          'Récords Personales',
      longestStreak:  'Racha más larga',
      maxInDay:       'Máx. en un día',
      longestSession: 'Sesión más larga',
      bestSession:    'Mejor sesión',
    },
    sections: {
      topArtists:       'Top 10 Artistas Históricos',
      genreDna:         'ADN de Géneros',
      hourDensity:      'Mapa de Densidad Horaria',
      hourRhythm:       'Ritmo de Escucha por Hora',
      yearlyEvolution:  'Evolución Musical 2015–2026',
      topHistoric:      'Top Histórico',
      musicalEras:      'Línea de Tiempo Musical',
      emotionalMap:     'Mapa Emocional Galáctico',
      personalityTitle: 'Perfil de Personalidad Musical',
      obsessionsTitle:  'Obsesiones Musicales & Loops',
      culturalTitle:    'ADN Cultural & Geográfico',
      innerTitle:       'Tu Universo Interior',
      artistTitle:      'Tu Perfil Artístico: Si Fueras Artista',
      insightsTitle:    'Lo que Revelan tus Datos',
      compareTitle:     'Spotify vs Last.fm',
      reportTitle:      'Tu Vida en Canciones',
      uploadTitle:      'Subir archivos reales',
    },
    hero: {
      years:     '11 Años de Biografía Sonora',
      enter:     'ENTRAR AL MUSEO SONORO',
      scrobbles: 'Scrobbles',
      hours:     'Horas',
      artists:   'Artistas',
      tracks:    'Canciones',
      days:      'Días Escuchados',
    },
    tabs: {
      artists:  'Artistas',
      tracks:   'Canciones',
      albums:   'Álbumes',
      genres:   'Géneros',
      years:    'Años',
    },
    misc: {
      plays:        'plays',
      printPdf:     'Imprimir / PDF',
      allEras:      'Todas las Eras',
      records:      'Récords',
      days:         'días',
      minutes:      'minutos',
      songs:        'canciones',
      less:         'Menos',
      more:         'Más',
      loading:      'Cargando...',
    },
    achievements: {
      title:        'Logros & Récords',
      subtitle:     (count: number) => `${count} logros desbloqueados en 11 años`,
      filterAll:    'Todos',
      tiers: {
        bronze:     'Bronce',
        silver:     'Plata',
        gold:       'Oro',
        platinum:   'Platino',
        legendary:  'Legendario',
      },
      radarTitle:   'Radar del Perfil Musical',
      radarMetrics: {
        volume:       'Volumen',
        diversity:    'Diversidad',
        consistency:  'Consistencia',
        exploration:  'Exploración',
        dedication:   'Dedicación',
        nostalgia:    'Nostalgia',
      },
      yourProfile:  'Tu Perfil',
      pointsByTier: 'Puntos por Nivel de Logro',
      pointsLegend: 'Puntos',
      totalPoints:  (pts: string) => `Total: ${pts} pts - Rango Legendario`,
    },
    dashboard: {
      notAvailable: 'no disponible',
      kpiTotalPlays: 'Plays Totales',
      kpiTotalPlaysSub: 'Registros únicos en Last.fm + Spotify',
      kpiHoursListened: 'Horas Escuchadas',
      kpiHoursListenedSub: (days: string | number) => `Aprox. ${days} días de música continua`,
      kpiUniqueArtists: 'Artistas Únicos',
      kpiUniqueArtistsSub: 'Artistas en 11 años de historial',
      kpiActiveDays: 'Días Activos',
      kpiActiveDaysSub: 'Días con al menos 1 reproducción',
      kpiBestYear: 'Mejor Año',
      kpiAvgPerDay: 'Promedio / Día',
      kpiAvgPerDaySub: (days: string | number) => `sobre ${days} días activos`,
      kpiNightListening: 'Escucha Nocturna',
      kpiNightListeningSub: 'madrugada 00–05 hrs',
      kpiPeakHour: 'Hora Pico',
      kpiPeakHourSub: 'hora con más reproducciones',
      personalRecords: 'Récords Personales',
      recordLongestStreak: 'Racha más larga',
      recordStreakUnit: (start: string, end: string) => `días · ${start} – ${end}`,
      recordStreakUnitFallback: 'días · requiere historial diario',
      recordMaxDay: 'Máx. en un día',
      recordMaxDayUnit: (date: string) => `plays · ${date}`,
      recordLongestSession: 'Sesión más larga',
      recordSessionUnit: (tracks: number) => `minutos · ${tracks} canciones`,
      recordBestSession: 'Mejor sesión',
      recordBestSessionUnit: (date: string) => `canciones · ${date}`,
      recordUnknownDate: 'fecha desconocida',
      topArtistsTitle: 'Top 10 Artistas Históricos',
      playsLegend: 'Plays',
      genreDnaTitle: 'ADN de Géneros',
      heatmapTitle: 'Mapa de Densidad Horaria',
      heatmapLess: 'Menos',
      heatmapMore: 'Más',
      heatmapFooter: 'Horizontal: 24 horas · Vertical: días de la semana',
      hourlyRhythmTitle: 'Ritmo de Escucha por Hora del Día',
      evolutionTitle: 'Evolución Musical 2015–2026',
      uniqueArtistsLegend: 'Artistas únicos',
    },
    innerWorld: {
      pageTitle: 'Tu Universo Interior',
      bannerTitle: '"Neópolis Lirioth" ✧ Tu Universo Sonoro',
      bannerBody: 'Un espacio personal donde el metalcore melódico se convierte en arquitectura, el synthwave en iluminación y el blackgaze en el cielo nocturno. Este universo es tuyo: oscuro, hermoso, en constante evolución.',
      colorPaletteTitle: 'Paleta de Colores Interna',
      colorPaletteIntro: 'Tu espectro visual es nocturno e híbrido, construido sobre Darksynth, Blackgaze y Synthwave:',
      colorNeonCyan: 'Cian Neón',
      colorCyberPink: 'Rosa Cyber',
      colorMysticPurple: 'Morado',
      colorAbyssBlack: 'Negro Abismo',
      colorElectricBlue: 'Azul Eléctrico',
      emotionalLandscapeTitle: 'Paisaje Emocional',
      emotionalLandscapeBody: 'Una autopista interminable bajo rascacielos negros con hologramas de neón cian. Llueve de forma constante, pero en el horizonte se asoma un amanecer luminoso y difuso. Catarsis en movimiento.',
      soundtrackTitle: 'Banda Sonora de tus Versiones',
      versionPast: 'Versión Pasada',
      versionPastDesc: 'Búsqueda melódica de conexión',
      versionPresent: 'Versión Presente',
      versionPresentDesc: 'Madurez y melancolía que brilla',
      versionFuture: 'Versión Futura',
      versionFutureDesc: 'Energía, ligereza y movimiento',
      imaginaryCityTitle: 'Ciudad Imaginaria',
      imaginaryCityName: '"Neópolis Lirioth"',
      imaginaryCityBody: 'Un bastión suspendido en el espacio, arquitectura gótica digital con glassmorphism. Silencioso en sus calles pero rebosante de frecuencias experimentales en su núcleo reactor de neón.',
      gamerDnaTitle: 'ADN Gamer & Fantasía',
      gamerDnaBody: 'Tu música conecta con mundos de rol futuristas (Cyberpunk 2077, Hades, NieR) y oscuridad fantasy épica. Los sintetizadores son tu "música de fondo de misión final".',
      archetypesTitle: 'Arquetipos de tu Identidad',
      archetypeExplorerName: 'El Explorador Melancólico',
      archetypeExplorerDesc: 'Busca belleza en la oscuridad',
      archetypeWarriorName: 'El Guerrero Emocional',
      archetypeWarriorDesc: 'Catarsis como combustible',
      archetypeArchitectName: 'El Arquitecto Sonoro',
      archetypeArchitectDesc: 'Construye mundos con frecuencias',
      archetypeFuturistName: 'El Futurista Nostálgico',
      archetypeFuturistDesc: 'Mira hacia adelante desde el pasado',
      lyricalThemesTitle: 'Temas Líricos Recurrentes',
      creativeIdentityTitle: 'Identidad Creativa → Arte',
      creativeIdentityIntro: 'Tu música puede convertirse en:',
    },
    statsDeepDive: {
      title: 'Estadísticas Profundas',
      kpiConsistency: 'Consistencia',
      kpiConsistencyDesc: 'Días activos / días totales',
      kpiExploration: 'Exploración',
      kpiExplorationDesc: 'Artistas por 1000 plays',
      kpiObsession: 'Obsesión',
      kpiObsessionDesc: 'Tasa de repetición',
      kpiPeakYear: 'Año Cumbre',
      kpiPeakYearDesc: (plays: string) => `${plays} plays`,
      heatmapTitle: 'Mapa de Actividad 11 Años',
      estimatedMonths: 'meses estimados',
      less: 'Menos',
      more: 'Más',
      monthCellTitle: (year: number, month: string, plays: string) => `${year} ${month}: ~${plays} plays`,
      clickYearHint: 'Haz clic en una fila para ver el desglose mensual',
      monthlyBreakdown: 'Desglose Mensual',
      peakLabel: 'Pico: ',
      playsCount: (plays: string) => `${plays} plays`,
      plays: 'Plays',
      weekdayPatternTitle: 'Patrón por Día de la Semana',
      genreTreemapTitle: 'Treemap de Géneros (por plays)',
      genreEvolutionTitle: 'Evolución de Plays & Descubrimiento 2015–2026',
      uniqueArtists: 'Artistas únicos',
      diversityPct: 'Diversidad %',
    },
    topHistorico: {
      title: 'Top Histórico',
      searchPlaceholder: 'Buscar…',
      tabArtists: 'Artistas',
      tabTracks: 'Canciones',
      tabAlbums: 'Álbumes',
      tabGenres: 'Géneros',
      tabYears: 'Años',
      top50Artists: 'Top 50 Artistas',
      top50Tracks: 'Top 50 Canciones',
      top50Albums: 'Top 50 Álbumes',
      top20Chart: 'Top 20 — Gráfico',
      genreTreemap: 'Treemap de Géneros',
      genreBreakdown: 'Desglose por Géneros',
      playsByYear: 'Reproducciones por Año (2015–2026)',
      playsLegend: 'Plays',
      uniqueArtistsLegend: 'Artistas únicos',
      resultsCount: (count: number) => `${count} resultados`,
      eraDiversityLine: (diversityIndex: number, uniqueArtists: number) =>
        `Diversidad ${diversityIndex}% · ${uniqueArtists} artistas`,
    },
    hiddenInsights: {
      title:                    'Lo que Revelan tus Datos y Quizás No Notabas',
      supportWeightTitle:       'La Importancia Secreta de Artistas de Apoyo',
      supportWeightBody:        (topArtistName: string, secondArtistName: string, secondArtistPlays: string | number, thirdArtistName?: string, thirdArtistPlays?: string) =>
        `Aunque ${topArtistName} domina la cima, artistas como ${secondArtistName} (${secondArtistPlays} plays)${thirdArtistName ? ` y ${thirdArtistName} (${thirdArtistPlays} plays)` : ''} revelan la capa estable de apoyo de tu escucha cotidiana.`,
      secondArtistFallback:     'tu segundo artista',
      sourceCrossCheckTitle:    'Cruce de Datos',
      sourceCrossCheckBody:     (matchRatePct: number) =>
        `La tasa actual de coincidencia/cobertura es ${matchRatePct}%.`,
      spotifyShortPlaysNote:    (shortPlaysCount: string | number) =>
        `Spotify también muestra ${shortPlaysCount} plays cortos bajo 30 segundos.`,
      timeResistantTracksTitle: 'Canciones que Resisten el Paso de los Años',
      timeResistantTracksBody:  (anchorTitle: string, firstArtist?: string, secondTitle?: string) =>
        `Pistas como ${anchorTitle}${firstArtist ? ` de ${firstArtist}` : ''}${secondTitle ? ` y ${secondTitle}` : ''} funcionan como anclas emocionales porque sobreviven la presión del ranking a lo largo de todo el archivo.`,
      anchorTrackFallback:      'tu cancion principal',
      nocturnalRegulationTitle: 'La Regulación Emocional Nocturna',
      nocturnalRegulationBody:  (nightRatio: number, longestStreakDays: number) =>
        `Tu patrón de escucha nocturna representa ${nightRatio}% de plays entre 00:00 y 05:59. Tu racha más larga detectada es de ${longestStreakDays} días, lo que sugiere que la música funciona como hábito estabilizador, no solo entretenimiento.`,
    },
    spotifyVsLastfm: {
      pageTitle:                    'Spotify vs Last.fm',
      verifiedScrobbles:            'Scrobbles verificados',
      matchWord:                    'coincidencia',
      artistsAndTracksOverlap:      'Overlap de artistas y tracks',
      measuredPlaysIncludesSkips:   'Plays medidos · incluye skips',
      estimatedPlays:               'Plays estimados',
      primaryScrobbleSource:        'Fuente primaria de scrobbles',
      measuredFromExport:           'Medido desde export',
      estimatedFromMatchRate:       'Estimado por match rate',
      matchRateLabel:               'Tasa de Coincidencia',
      normalizedSourceOverlap:      'Overlap normalizado entre fuentes',
      shortExtraPlaysLabel:         'Plays cortos / extra',
      shortExtraPlaysSub:           'Skips, previews o plays solo-Spotify',
      capabilitiesComparisonTitle:  'Comparación de Capacidades',
      hiddenInsightsTitle:          'Lo que el cruce de datos revela',
      dataQualityNoteTitle:         'Nota sobre la calidad de datos',
      estimatedValuesDisclaimer:    'Los valores de Spotify marcados como estimados son interpretativos, no conteos verificados del export.',
      yourTopArtistFallback:        'tu artista principal',
      yourSecondWaveFallback:       'tu segunda ola',
      playsByYearTitle:             (comparisonLabel: string) => `Plays por Año - Last.fm vs ${comparisonLabel}`,
      insightDominantArtistsTitle:  'Artistas que dominan en datos',
      insightDominantArtistsBody:   (topArtistName: string, topArtistPlays: string, secondArtistName: string) =>
        `${topArtistName} lidera con ${topArtistPlays} plays. Compararlo con artistas como ${secondArtistName} ayuda a separar lealtad cotidiana de escucha emocional consciente.`,
      insightSkipsTitle:            'Skips y plays cortos revelan exploración',
      insightSkipsBody:             (shortPlays: string) =>
        `Spotify aporta ${shortPlays} reproducciones cortas o solo-Spotify en esta vista. Esa es la capa exploratoria: previews, skips y busquedas antes de que caiga la cancion correcta.`,
      insightTwoYearArcTitle:       (periodLabel: string) => `${periodLabel}: el arco de dos años más fuerte`,
      insightTwoYearArcBody:        (peakPlays: string) =>
        `El periodo de dos años más fuerte contiene ${peakPlays} plays. Es el capitulo mas denso estadisticamente del dataset actual.`,
      insightNightModeTitle:        'La madrugada es un modo distinto',
      insightNightModeBody:         (nightPct: number) =>
        `${nightPct}% de los plays ocurren entre 00:00 y 05:59. Eso le da a la app un eje nocturno medible en vez de tratar todos los plays como iguales.`,
      insightOverlapTitle:          'El overlap debe leerse como confianza',
      insightOverlapBody:           (overlapTracks: number) =>
        `${overlapTracks} canciones normalizadas aparecen en ambas fuentes cuando subes ambas. El resto no son errores: son evidencia de comportamiento especifico por plataforma.`,
      radarHistory: 'Historial',
      radarAccuracy: 'Precisión',
      radarCoverage: 'Cobertura',
      radarMetadata: 'Metadatos',
      radarSkips: 'Skips',
      radarContext: 'Contexto',
      lastfmExactTimestamps: 'Timestamps exactos',
      lastfmFullAlbumData: 'Registro de álbum completo',
      lastfmNoSkipData: 'Sin datos de skip',
      lastfmNoPlaylistContext: 'Sin contexto de playlist',
      spotifySkipDataIncluded: 'Datos de skip incluidos',
      spotifyPlaylistContext: 'Contexto de playlist',
      spotifyOfflineDevice: 'Offline / dispositivo',
      spotifyEmptyPre2015: 'Historial pre-2015 vacío',
    },
    eraExplorer: {
      title: 'Línea de Tiempo Musical',
      yearActivity: 'Actividad del año',
      playsCount: (plays: string | number) => `${plays} plays`,
      interpretiveReading: 'Lectura Interpretativa',
      statsFor: (year: number) => `Datos de ${year}`,
      statPlays: 'Plays',
      statArtists: 'Artistas',
      statTracks: 'Canciones',
      statDiversity: 'Diversidad',
      flagshipArtist: 'Artista Insignia',
      anthemOfYear: 'Himno del Año',
      chapterOf: (current: number, total: number, year: number) => `Capítulo ${current} de ${total} ✧ ${year}`,
      allEras: 'Todas las Eras',
      fallbackInterpretation: (
        year: number,
        topArtist: string,
        plays: string,
        uniqueArtists: number,
        daypart: string,
      ) =>
        `${year} está liderado por ${topArtist}, con ${plays} plays y ${uniqueArtists} artistas. Los datos apuntan a un capítulo marcado por repetición, descubrimiento y la ventana de escucha ${daypart}.`,
    },
    artistIdentity: {
      title: 'Tu Perfil Artístico: Si Fueras Artista',
      suggestedAlias: 'Alias Artístico Sugerido',
      possibleSound: 'Tu Posible Sonido',
      idealTempo: 'Tempo Ideal',
      keyInfluences: 'Influencias Clave',
      visualAesthetic: 'Estética Visual & Escenarios',
      outfitAndLights: 'Vestuario & Luces:',
      outfitAndLightsDesc: 'Ropa cyberpunk en negro mate, detalles con LEDs interactivos que reaccionan a las frecuencias del bajo. Luz degradada cian y violeta.',
      concertConcept: 'Concepto de Concierto:',
      concertConceptDesc: (liveShow: string) => `${liveShow} reactivos que dibujan montañas geométricas y lluvia de código de neón en tiempo real detrás tuyo.`,
      firstEpConcept: 'Concepto de tu Primer EP',
      tracklist: 'Lista de Canciones (Tracklist)',
      albumArtConcept: 'Arte de Portada (Concepto)',
    },
    personalityRadar: {
      profileTitle: 'Perfil de Personalidad Musical',
      radarTitle: 'Radar de Identidad Musical',
      evidenceLabel: 'Evidencia en tus datos:',
      strengthLabel: 'Fortaleza / Lado Positivo',
      challengeLabel: 'Desafío / Lado Oscuro',
      tipLabel: 'Consejo de Bienestar Musical',
      archetypesTitle: 'Tus Arquetipos Musicales Activos',
      aestheticLabel: 'Estética:',
      strengthColonLabel: 'Fortaleza:',
      challengeColonLabel: 'Desafío:',
      traitLabels: {
        sensibilidad_emocional: 'Sensibilidad Emocional',
        nostalgia: 'Nostalgia Estética',
        energia: 'Energía & Dopamina',
        oscuridad_estetica: 'Oscuridad Estética',
        creatividad: 'Creatividad & Exploración',
        rebeldia: 'Fuerza Rebelde / Catarsis',
        futurismo: 'Futurismo / Sintetizadores',
      },
    },
    heroSection: {
      badge: '✨ 11 Años de Biografía Sonora',
      subtitle: '✧ El Universo Musical de Lirioth ✧',
      description: 'Un espacio ornamental, emocional y estadístico que explora tu identidad, tus etapas de vida y tus bandas de transformación. Tu música no es solo una lista de reproducción; es la banda sonora de tu propia evolución.',
      quote: {
        before: '"Tu núcleo musical está construido con capas de catarsis, noches de neón, shoegaze luminoso y post-hardcore melódico. Los datos sugieren que vuelves recurrentemente a tus anclas emocionales como ',
        midA: ' para recargar tu fuerza y a canciones refugio como ',
        midB: ' de ',
        after: ' para sanar y crear mundos imaginarios."',
      },
    },
    uploader: {
      title: 'Sube tus datos reales',
      dropHintBefore: 'Arrastra tu ',
      dropHintMiddle: ' y/o ',
      dropHintAfter: ' aquí.',
      browseButton: 'Examinar archivos localmente',
      dropZoneAriaLabel: 'Subir archivos de historial musical',
      privacyNote: 'Los archivos se procesan localmente en tu navegador. Campos sensibles de Spotify como IP se ignoran.',
      mergeNote: 'Puedes subir Last.fm y Spotify juntos para ver estadisticas fusionadas, overlap, skips, plataformas y paises.',
      processingStatus: 'Procesando y analizando tu historia...',
      noFilesError: 'Por favor, sube un CSV de Last.fm o archivos JSON de Spotify Extended Streaming History.',
      processingError: 'Error al procesar los archivos. Revisa el formato.',
      successMessage: (fileCount: number, totalPlays: string, uniqueArtists: string, skipRate: number) =>
        `Se cargaron ${fileCount} archivo(s): ${totalPlays} plays, ${uniqueArtists} artistas, ${skipRate}% de skips en Spotify.`,
    },
    cultural: {
      title: 'ADN Cultural & Geográfico',
      heroTitle: 'Tu Huella Sonora Migrante',
      heroDesc: (countryCount: number) =>
        `Tu música refleja una identidad globalizada y única: la raíz venezolana, la experiencia israelí y la cultura digital angloparlante conviven en perfecta tensión creativa. Escuchas en 4+ idiomas desde ${countryCount}+ países.`,
      artistsByCountry: 'Países de tus Artistas',
      languageDistribution: 'Distribución de Idiomas',
      conclusionTitle: 'Conclusión del ADN Cultural',
      conclusionDesc: 'Tu perfil musical se niega a ser encasillado. Es una mezcla líquida donde conviven guitarras nórdicas, rock en hebreo, synthwave cyberpunk y groove alternativo angloparlante. Esta diversidad es tu mayor fortaleza creativa.',
    },
    obsessionDetector: {
      title:                'Obsesiones Musicales & Loops',
      hyperfixationsTitle:  'Hiperfijaciones Musicales',
      hyperfixationsDesc:   'Canciones reproducidas repetidamente en bucle durante un mismo día. Revela momentos de obsesión emocional o foco intensivo.',
      noHyperfixations:     'No se detectaron hiperfijaciones extremas en tus datos.',
      marathonsTitle:       'Maratones de Escucha (Sesiones)',
      marathonsDesc:        'Grupos de canciones reproducidas secuencialmente con intervalos de silencio menores a 60 minutos. Revela maratones de estudio, viajes o noches en vela.',
      sessionStart:         'Inicio de sesión:',
      estDuration:          'Duración est.:',
      volume:               'Volumen:',
      volumeUnit:           'canciones',
      dominantArtist:       'Artista dominante:',
    },
    emotionalMap: {
      artistCoordinates: 'Coordenadas de Artistas',
      axesLabel:         'Ejes: Energía vs Positividad',
      positivityAxis:    'Positividad (Valence)',
      positivityName:    'Positividad',
      energyAxis:        'Energía',
      frequencyLabel:    'Frecuencia',
      artistsLegend:     'Artistas',
      darkSide:          '← Melancólico / Oscuro',
      brightSide:        'Optimista / Brillante →',
      tabLament:         'Lamento',
      tabCatharsis:      'Catarsis',
      tabDose:           'Dosis',
      tabFocus:          'Foco',
      keyArtistsLabel:   'Artistas clave:',
      refugeTracksLabel: 'Canciones del refugio:',
      dominantTimeLabel: 'Horario dominante:',
    },
    finalReport: {
      pageTitle: 'Tu Vida en Canciones',
      printButton: 'Imprimir / PDF',
      coverBadge: 'Nova Music Lab · Informe Personal 2026',
      coverHeadlinePre: 'Lo que ',
      coverHeadlineHighlight: '11 años de música',
      coverHeadlinePost: 'revelan sobre mí',
      coverSubtitlePre: 'Un ensayo para ',
      coverSubtitleName: 'Kevin Cusnir / Lirioth Teltanion',
      statScrobbles: 'Scrobbles',
      statHours: 'Horas',
      statArtists: 'Artistas',
      statTracks: 'Canciones',
      s1Roman: 'I',
      s1Title: 'El Valor de una Huella Sonora',
      s1Pre: 'Kevin, la música que escuchamos es el registro sísmico de nuestro mundo interior. Al analizar tus',
      s1Mid: 'registrados desde 2015, no estamos leyendo estadísticas — estamos leyendo un diario emocional íntimo. Tus',
      s1Post: 'hablan de mudanzas, noches de hiperfijación y mañanas de energía pura.',
      s1ScrobblesLabel: 'scrobbles',
      s1HoursLabel: 'horas escuchadas',
      s1Quote: 'Tu música no es un playlist. Es el mapa de todos los mundos que has habitado.',
      s2Roman: 'II',
      s2Title: 'Las Eras: Capítulos de una Vida',
      s2Pre: 'En 2015,',
      s2ArtistName: 'Carpenter Brut',
      s2ArtistIntro: 'abrió los primeros capítulos. En 2018, tu racha activa de',
      s2StreakLabel: 'días consecutivos',
      s2Mid: (peakLabel: string) => `refleja intensidad de vida sin precedentes. El arco ${peakLabel} es tu cumbre musical con`,
      s2CombinedLabel: 'scrobbles combinados',
      s2Quote: "'In Blur' no es solo una canción. Es el himno de una versión tuya que aprendió a brillar desde la oscuridad.",
      s3Roman: 'III',
      s3Title: 'El ADN: Quién Eres según tu Música',
      s3Pre: 'Con',
      s3ArtistsLabel: 'artistas únicos',
      s3Mid: 'y',
      s3TracksLabel: 'canciones únicas',
      s3ArchetypeIntro: 'eres un',
      s3Archetype: 'Explorador de Alta Intensidad',
      s3NightIntro: 'Tu',
      s3NightLabel: (nightRatio: number) => `${nightRatio}% de escucha nocturna`,
      s3Post: 'revela que la música es también regulación emocional: silencio habitado con frecuencias.',
      s3Quote: 'No escuchas música de fondo. Escuchas como si cada canción mereciera ser recordada.',
      s4Roman: 'IV',
      s4Title: 'Lirioth: La Proyección Creativa',
      s4Pre: 'Tu alias',
      s4AliasLabel: 'Lirioth Teltanion',
      s4Post: 'es la síntesis de todo lo que tu música ha construido. El sonido que te define — guitarras de post-hardcore, sintetizadores cyberpunk y groove alternativo — es una propuesta artística lista para producción musical, videojuegos, arte digital o storytelling.',
      s4Quote: 'Tu próxima era no será de consumo. Será de creación.',
      s5Roman: 'V',
      s5Title: 'Seguir Escuchando para Seguir Siendo',
      s5Pre: 'Kevin, tu historia demuestra sensibilidad emocional extraordinaria y resiliencia que sabe resurgir. Cada uno de tus',
      s5DaysLabel: 'días activos',
      s5Post: (topArtist: string, topTrack: string) => `es evidencia de que la música ha sido lenguaje, terapia, identidad y futuro a la vez. ${topArtist} y "${topTrack}" siempre estarán ahí.`,
      footerName: '✧ LIRIOTH TELTANION ✧',
      footerSubtitle: 'Nova Music Lab · Museo Personal · 2026',
    },
  },
  en: {
    appTitle: 'NOVA MUSIC LAB',
    appSubtitle: "Lirioth's Musical Universe",
    user: 'User',
    loadData: 'Load Data',
    nav: {
      dashboard:   'Dashboard',
      eras:        'Musical Eras',
      top:         'All-Time Top',
      personality: 'Personality',
      emotions:    'Emotional Map',
      obsessions:  'Obsessions',
      cultural:    'Cultural DNA',
      inner:       'Inner World',
      artist:      'If I Were an Artist',
      insights:    'Hidden Insights',
      compare:     'Spotify vs Last.fm',
      statsPro:    'Stats Pro',
      achievements:'Achievements',
      report:      'Final Essay',
      upload:      'Upload Files',
    },
    kpi: {
      totalPlays:    'Total Plays',
      hours:         'Hours Listened',
      artists:       'Unique Artists',
      activeDays:    'Active Days',
      bestYear:      'Best Year',
      avgPerDay:     'Avg / Day',
      nightRatio:    'Night Listening',
      peakHour:      'Peak Hour',
      uniqueTracks:  'Unique Tracks',
      uniqueAlbums:  'Unique Albums',
    },
    records: {
      title:          'Personal Records',
      longestStreak:  'Longest streak',
      maxInDay:       'Max in one day',
      longestSession: 'Longest session',
      bestSession:    'Best session',
    },
    sections: {
      topArtists:       'Top 10 All-Time Artists',
      genreDna:         'Genre DNA',
      hourDensity:      'Hourly Density Map',
      hourRhythm:       'Listening Rhythm by Hour',
      yearlyEvolution:  'Musical Evolution 2015–2026',
      topHistoric:      'All-Time Top',
      musicalEras:      'Musical Timeline',
      emotionalMap:     'Galactic Emotional Map',
      personalityTitle: 'Musical Personality Profile',
      obsessionsTitle:  'Musical Obsessions & Loops',
      culturalTitle:    'Cultural & Geographic DNA',
      innerTitle:       'Your Inner Universe',
      artistTitle:      'Your Artist Profile: If You Were an Artist',
      insightsTitle:    'What Your Data Reveals',
      compareTitle:     'Spotify vs Last.fm',
      reportTitle:      'Your Life in Songs',
      uploadTitle:      'Upload real files',
    },
    hero: {
      years:     '11 Years of Musical Biography',
      enter:     'ENTER THE SOUND MUSEUM',
      scrobbles: 'Scrobbles',
      hours:     'Hours',
      artists:   'Artists',
      tracks:    'Tracks',
      days:      'Listening Days',
    },
    tabs: {
      artists:  'Artists',
      tracks:   'Tracks',
      albums:   'Albums',
      genres:   'Genres',
      years:    'Years',
    },
    misc: {
      plays:        'plays',
      printPdf:     'Print / PDF',
      allEras:      'All Eras',
      records:      'Records',
      days:         'days',
      minutes:      'minutes',
      songs:        'songs',
      less:         'Less',
      more:         'More',
      loading:      'Loading...',
    },
    achievements: {
      title:        'Achievements & Records',
      subtitle:     (count: number) => `${count} unlocked achievements across 11 years`,
      filterAll:    'All',
      tiers: {
        bronze:     'Bronze',
        silver:     'Silver',
        gold:       'Gold',
        platinum:   'Platinum',
        legendary:  'Legendary',
      },
      radarTitle:   'Music Profile Radar',
      radarMetrics: {
        volume:       'Volume',
        diversity:    'Diversity',
        consistency:  'Consistency',
        exploration:  'Exploration',
        dedication:   'Dedication',
        nostalgia:    'Nostalgia',
      },
      yourProfile:  'Your Profile',
      pointsByTier: 'Achievement Points by Tier',
      pointsLegend: 'Points',
      totalPoints:  (pts: string) => `Total: ${pts} pts - Legendary Rank`,
    },
    dashboard: {
      notAvailable: 'not available',
      kpiTotalPlays: 'Total Plays',
      kpiTotalPlaysSub: 'Unique records in Last.fm + Spotify',
      kpiHoursListened: 'Hours Listened',
      kpiHoursListenedSub: (days: string | number) => `Approx. ${days} days of continuous music`,
      kpiUniqueArtists: 'Unique Artists',
      kpiUniqueArtistsSub: 'Artists across 11 years of history',
      kpiActiveDays: 'Active Days',
      kpiActiveDaysSub: 'Days with at least 1 registered play',
      kpiBestYear: 'Best Year',
      kpiAvgPerDay: 'Avg / Day',
      kpiAvgPerDaySub: (days: string | number) => `over ${days} active days`,
      kpiNightListening: 'Night Listening',
      kpiNightListeningSub: 'midnight 00–05 hrs',
      kpiPeakHour: 'Peak Hour',
      kpiPeakHourSub: 'hour with most historical plays',
      personalRecords: 'Personal Records',
      recordLongestStreak: 'Longest streak',
      recordStreakUnit: (start: string, end: string) => `days · ${start} – ${end}`,
      recordStreakUnitFallback: 'days · needs daily source',
      recordMaxDay: 'Max in one day',
      recordMaxDayUnit: (date: string) => `plays · ${date}`,
      recordLongestSession: 'Longest session',
      recordSessionUnit: (tracks: number) => `minutes · ${tracks} songs`,
      recordBestSession: 'Best session',
      recordBestSessionUnit: (date: string) => `songs · ${date}`,
      recordUnknownDate: 'unknown date',
      topArtistsTitle: 'Top 10 All-Time Artists',
      playsLegend: 'Plays',
      genreDnaTitle: 'Genre DNA',
      heatmapTitle: 'Hourly Density Map',
      heatmapLess: 'Less',
      heatmapMore: 'More',
      heatmapFooter: 'Horizontal: 24 hours · Vertical: days of the week',
      hourlyRhythmTitle: 'Listening Rhythm by Hour',
      evolutionTitle: 'Musical Evolution 2015–2026',
      uniqueArtistsLegend: 'Unique Artists',
    },
    innerWorld: {
      pageTitle: 'Your Inner Universe',
      bannerTitle: '"Neópolis Lirioth" ✧ Your Sonic Universe',
      bannerBody: 'A personal space where melodic metalcore becomes architecture, synthwave becomes lighting, and blackgaze becomes the night sky. This universe is yours: dark, beautiful, constantly evolving.',
      colorPaletteTitle: 'Internal Color Palette',
      colorPaletteIntro: 'Your visual spectrum is nocturnal and hybrid, built on Darksynth, Blackgaze and Synthwave:',
      colorNeonCyan: 'Neon Cyan',
      colorCyberPink: 'Cyber Pink',
      colorMysticPurple: 'Mystic Purple',
      colorAbyssBlack: 'Abyss Black',
      colorElectricBlue: 'Electric Blue',
      emotionalLandscapeTitle: 'Emotional Landscape',
      emotionalLandscapeBody: 'An endless highway surrounded by black skyscrapers with neon cyan holograms. It rains constantly, but on the horizon a luminous dawn appears. Catharsis in motion: intensity advancing toward the light.',
      soundtrackTitle: 'Soundtrack of Your Versions',
      versionPast: 'Past Version',
      versionPastDesc: 'Melodic search for connection',
      versionPresent: 'Present Version',
      versionPresentDesc: 'Maturity and glowing melancholy',
      versionFuture: 'Future Version',
      versionFutureDesc: 'Energy, lightness and movement',
      imaginaryCityTitle: 'Imaginary City',
      imaginaryCityName: '"Neópolis Lirioth"',
      imaginaryCityBody: 'A fortress suspended in space, digital gothic architecture with glassmorphism. Silent in its streets but full of experimental radio frequencies in its neon reactor core.',
      gamerDnaTitle: 'Gamer & Fantasy DNA',
      gamerDnaBody: 'Your music connects with futuristic RPG worlds (Cyberpunk 2077, Hades, NieR) and dark epic fantasy. Synthesizers are your "final boss music".',
      archetypesTitle: 'Identity Archetypes',
      archetypeExplorerName: 'The Melancholic Explorer',
      archetypeExplorerDesc: 'Seeks beauty in darkness',
      archetypeWarriorName: 'The Emotional Warrior',
      archetypeWarriorDesc: 'Catharsis as fuel',
      archetypeArchitectName: 'The Sonic Architect',
      archetypeArchitectDesc: 'Builds worlds with frequencies',
      archetypeFuturistName: 'The Nostalgic Futurist',
      archetypeFuturistDesc: 'Looks forward from the past',
      lyricalThemesTitle: 'Recurring Lyrical Themes',
      creativeIdentityTitle: 'Creative Identity → Art',
      creativeIdentityIntro: 'Your music can become:',
    },
    statsDeepDive: {
      title: 'Pro Statistics',
      kpiConsistency: 'Consistency',
      kpiConsistencyDesc: 'Active days / total days',
      kpiExploration: 'Exploration',
      kpiExplorationDesc: 'Artists per 1000 plays',
      kpiObsession: 'Obsession',
      kpiObsessionDesc: 'Repetition rate',
      kpiPeakYear: 'Peak Year',
      kpiPeakYearDesc: (plays: string) => `${plays} plays`,
      heatmapTitle: '11-Year Activity Heatmap',
      estimatedMonths: 'estimated months',
      less: 'Less',
      more: 'More',
      monthCellTitle: (year: number, month: string, plays: string) => `${year} ${month}: ~${plays} plays`,
      clickYearHint: 'Click a year row to see monthly breakdown below',
      monthlyBreakdown: 'Monthly Breakdown',
      peakLabel: 'Peak: ',
      playsCount: (plays: string) => `${plays} plays`,
      plays: 'Plays',
      weekdayPatternTitle: 'Day-of-Week Pattern',
      genreTreemapTitle: 'Genre Treemap (by plays)',
      genreEvolutionTitle: 'Plays & Artist Discovery 2015–2026',
      uniqueArtists: 'Unique Artists',
      diversityPct: 'Diversity %',
    },
    topHistorico: {
      title: 'All-Time Top',
      searchPlaceholder: 'Search…',
      tabArtists: 'Artists',
      tabTracks: 'Tracks',
      tabAlbums: 'Albums',
      tabGenres: 'Genres',
      tabYears: 'Years',
      top50Artists: 'Top 50 Artists',
      top50Tracks: 'Top 50 Tracks',
      top50Albums: 'Top 50 Albums',
      top20Chart: 'Top 20 — Chart',
      genreTreemap: 'Genre Treemap',
      genreBreakdown: 'Genre Breakdown Bar',
      playsByYear: 'Plays by Year (2015–2026)',
      playsLegend: 'Plays',
      uniqueArtistsLegend: 'Unique Artists',
      resultsCount: (count: number) => `${count} results`,
      eraDiversityLine: (diversityIndex: number, uniqueArtists: number) =>
        `Diversity ${diversityIndex}% · ${uniqueArtists} artists`,
    },
    hiddenInsights: {
      title:                    'What Your Data Reveals That You May Not Have Noticed',
      supportWeightTitle:       'The Secret Weight of Support Artists',
      supportWeightBody:        (topArtistName: string, secondArtistName: string, secondArtistPlays: string | number, thirdArtistName?: string, thirdArtistPlays?: string) =>
        `Although ${topArtistName} leads the archive, artists like ${secondArtistName} (${secondArtistPlays} plays)${thirdArtistName ? ` and ${thirdArtistName} (${thirdArtistPlays} plays)` : ''} reveal the stable support layer of your listening.`,
      secondArtistFallback:     'your second artist',
      sourceCrossCheckTitle:    'Source Cross-Check',
      sourceCrossCheckBody:     (matchRatePct: number) =>
        `The current match/coverage rate is ${matchRatePct}%.`,
      spotifyShortPlaysNote:    (shortPlaysCount: string | number) =>
        `Spotify also shows ${shortPlaysCount} short plays under 30 seconds.`,
      timeResistantTracksTitle: 'Tracks That Resist Time',
      timeResistantTracksBody:  (anchorTitle: string, firstArtist?: string, secondTitle?: string) =>
        `Tracks like ${anchorTitle}${firstArtist ? ` by ${firstArtist}` : ''}${secondTitle ? ` and ${secondTitle}` : ''} behave as emotional anchors because they survive the ranking pressure across the whole archive.`,
      anchorTrackFallback:      'your main track',
      nocturnalRegulationTitle: 'Nocturnal Emotional Regulation',
      nocturnalRegulationBody:  (nightRatio: number, longestStreakDays: number) =>
        `Your late-night pattern represents ${nightRatio}% of total plays between 00:00 and 05:59. Your strongest detected streak is ${longestStreakDays} days, which suggests music is a stabilizing habit, not only entertainment.`,
    },
    spotifyVsLastfm: {
      pageTitle:                    'Spotify vs Last.fm',
      verifiedScrobbles:            'Verified scrobbles',
      matchWord:                    'match',
      artistsAndTracksOverlap:      'Artist and track overlap',
      measuredPlaysIncludesSkips:   'Measured plays · includes skips',
      estimatedPlays:               'Estimated plays',
      primaryScrobbleSource:        'Primary scrobble source',
      measuredFromExport:           'Measured from export',
      estimatedFromMatchRate:       'Estimated from match rate',
      matchRateLabel:               'Match Rate',
      normalizedSourceOverlap:      'Normalized source overlap',
      shortExtraPlaysLabel:         'Short / Extra Plays',
      shortExtraPlaysSub:           'Skips, previews or Spotify-only plays',
      capabilitiesComparisonTitle:  'Capability Comparison',
      hiddenInsightsTitle:          'What the data crossover reveals',
      dataQualityNoteTitle:         'Data quality note',
      estimatedValuesDisclaimer:    'Spotify values marked as estimated are interpretive, not verified export counts.',
      yourTopArtistFallback:        'your top artist',
      yourSecondWaveFallback:       'your second wave',
      playsByYearTitle:             (comparisonLabel: string) => `Plays by Year - Last.fm vs ${comparisonLabel}`,
      insightDominantArtistsTitle:  'Artists that dominate the data',
      insightDominantArtistsBody:   (topArtistName: string, topArtistPlays: string, secondArtistName: string) =>
        `${topArtistName} leads with ${topArtistPlays} plays. The contrast with artists like ${secondArtistName} helps separate everyday background loyalty from more conscious emotional listening.`,
      insightSkipsTitle:            'Short plays and skips reveal exploration',
      insightSkipsBody:             (shortPlays: string) =>
        `Spotify contributes ${shortPlays} short or Spotify-only plays in this view. That is the exploratory layer: previews, skips and searches before the right track lands.`,
      insightTwoYearArcTitle:       (periodLabel: string) => `${periodLabel}: strongest two-year arc`,
      insightTwoYearArcBody:        (peakPlays: string) =>
        `The strongest two-year period contains ${peakPlays} plays. This is the most statistically dense chapter in the current dataset.`,
      insightNightModeTitle:        'Night listening is a distinct mode',
      insightNightModeBody:         (nightPct: number) =>
        `${nightPct}% of plays happen between 00:00 and 05:59. That gives the app a measurable nocturnal axis instead of treating all plays as equal.`,
      insightOverlapTitle:          'Overlap should be treated as confidence',
      insightOverlapBody:           (overlapTracks: number) =>
        `${overlapTracks} normalized tracks appear in both sources when both are uploaded. The rest are not errors; they are evidence of platform-specific behavior.`,
      radarHistory: 'History',
      radarAccuracy: 'Accuracy',
      radarCoverage: 'Coverage',
      radarMetadata: 'Metadata',
      radarSkips: 'Skips',
      radarContext: 'Context',
      lastfmExactTimestamps: 'Exact timestamps',
      lastfmFullAlbumData: 'Full album data',
      lastfmNoSkipData: 'No skip data',
      lastfmNoPlaylistContext: 'No playlist context',
      spotifySkipDataIncluded: 'Skip data included',
      spotifyPlaylistContext: 'Playlist context',
      spotifyOfflineDevice: 'Offline / device info',
      spotifyEmptyPre2015: 'Empty pre-2015 history',
    },
    eraExplorer: {
      title: 'Musical Timeline',
      yearActivity: 'Year activity',
      playsCount: (plays: string | number) => `${plays} plays`,
      interpretiveReading: 'Interpretive Reading',
      statsFor: (year: number) => `Stats for ${year}`,
      statPlays: 'Plays',
      statArtists: 'Artists',
      statTracks: 'Tracks',
      statDiversity: 'Diversity',
      flagshipArtist: 'Flagship Artist',
      anthemOfYear: 'Anthem of the Year',
      chapterOf: (current: number, total: number, year: number) => `Chapter ${current} of ${total} ✧ ${year}`,
      allEras: 'All Eras',
      fallbackInterpretation: (
        year: number,
        topArtist: string,
        plays: string,
        uniqueArtists: number,
        daypart: string,
      ) =>
        `${year} is led by ${topArtist}, with ${plays} plays and ${uniqueArtists} artists. The data points to a chapter shaped by repetition, discovery and the ${daypart} listening window.`,
    },
    personalityRadar: {
      profileTitle: 'Musical Personality Profile',
      radarTitle: 'Musical Identity Radar',
      evidenceLabel: 'Musical Evidence',
      strengthLabel: 'Strength / Positive Side',
      challengeLabel: 'Challenge / Shadow Side',
      tipLabel: 'Musical Wellbeing Tip',
      archetypesTitle: 'Your Active Musical Archetypes',
      aestheticLabel: 'Aesthetic:',
      strengthColonLabel: 'Strength:',
      challengeColonLabel: 'Challenge:',
      traitLabels: {
        sensibilidad_emocional: 'Emotional Sensitivity',
        nostalgia: 'Aesthetic Nostalgia',
        energia: 'Energy & Dopamine',
        oscuridad_estetica: 'Aesthetic Darkness',
        creatividad: 'Creativity & Exploration',
        rebeldia: 'Rebellious Force / Catharsis',
        futurismo: 'Futurism / Synthesizers',
      },
    },
    artistIdentity: {
      title: 'Your Artist Profile: If You Were an Artist',
      suggestedAlias: 'Suggested Artist Alias',
      possibleSound: 'Your Possible Sound',
      idealTempo: 'Ideal Tempo',
      keyInfluences: 'Key Influences',
      visualAesthetic: 'Visual Aesthetic & Stage Concept',
      outfitAndLights: 'Outfit & Lights:',
      outfitAndLightsDesc: 'Matte black cyberpunk clothing with interactive LEDs that react to bass frequencies. Cyan and violet gradient lighting.',
      concertConcept: 'Concert Concept:',
      concertConceptDesc: (liveShow: string) => `${liveShow} Reactive 3D visuals drawing geometric mountains and neon rain in real time.`,
      firstEpConcept: 'Your First EP Concept',
      tracklist: 'Tracklist',
      albumArtConcept: 'Album Art (Concept)',
    },
    heroSection: {
      badge: '✨ 11 Years of Musical Biography',
      subtitle: '✧ Musical Universe of Lirioth ✧',
      description: 'An ornamental, emotional and statistical space that explores your identity, your life stages and your transformative bands. Your music is not just a playlist — it is the soundtrack of your own evolution.',
      quote: {
        before: '"Your musical core is built with layers of catharsis, neon nights, luminous shoegaze and melodic post-hardcore. Data suggests you recurrently return to your emotional anchors like ',
        midA: ' to recharge your strength, and to refuge songs like ',
        midB: ' by ',
        after: ' to heal and build imaginary worlds."',
      },
    },
    uploader: {
      title: 'Upload your real music data',
      dropHintBefore: 'Drop your ',
      dropHintMiddle: ' and/or ',
      dropHintAfter: ' files here.',
      browseButton: 'Browse local files',
      dropZoneAriaLabel: 'Upload music history files',
      privacyNote: 'Files are parsed locally in your browser. Sensitive Spotify fields such as IP address are ignored.',
      mergeNote: 'You can upload Last.fm and Spotify together for merged stats, overlap, skips, platforms and countries.',
      processingStatus: 'Processing and analyzing your history...',
      noFilesError: 'Please upload a Last.fm CSV or Spotify Extended Streaming History JSON files.',
      processingError: 'Error processing the files. Please check the export format.',
      successMessage: (fileCount: number, totalPlays: string, uniqueArtists: string, skipRate: number) =>
        `Loaded ${fileCount} file(s): ${totalPlays} plays, ${uniqueArtists} artists, ${skipRate}% Spotify skip rate.`,
    },
    cultural: {
      title: 'Cultural & Geographic DNA',
      heroTitle: 'Your Migrant Sonic Footprint',
      heroDesc: (countryCount: number) =>
        `Your music reflects a uniquely globalized identity: Venezuelan roots, the Israeli experience and digital English-speaking culture coexist in perfect creative tension. You listen in 4+ languages from ${countryCount}+ countries.`,
      artistsByCountry: 'Your Artists by Country',
      languageDistribution: 'Language Distribution',
      conclusionTitle: 'Cultural DNA Conclusion',
      conclusionDesc: "Your musical profile refuses to be boxed into a single border. It's a liquid blend where Nordic melancholic guitars, Hebrew rock, cyberpunk synthwave and English-speaking alternative groove coexist. This diversity is your greatest creative strength.",
    },
    obsessionDetector: {
      title:                'Musical Obsessions & Loops',
      hyperfixationsTitle:  'Music Hyperfixations',
      hyperfixationsDesc:   'Songs played repeatedly on loop during a single day. Reveals moments of emotional obsession or intensive focus.',
      noHyperfixations:     'No extreme hyperfixations were detected in your data.',
      marathonsTitle:       'Listening Marathons (Sessions)',
      marathonsDesc:        'Groups of songs played sequentially with silence gaps under 60 minutes. Reveals study marathons, trips, or late-night sessions.',
      sessionStart:         'Session start:',
      estDuration:          'Est. duration:',
      volume:               'Volume:',
      volumeUnit:           'songs',
      dominantArtist:       'Dominant artist:',
    },
    emotionalMap: {
      artistCoordinates: 'Artist Coordinates',
      axesLabel:         'Axes: Energy vs Positivity',
      positivityAxis:    'Positivity (Valence)',
      positivityName:    'Positivity',
      energyAxis:        'Energy',
      frequencyLabel:    'Frequency',
      artistsLegend:     'Artists',
      darkSide:          '← Melancholic / Dark',
      brightSide:        'Optimistic / Bright →',
      tabLament:         'Lament',
      tabCatharsis:      'Catharsis',
      tabDose:           'Dose',
      tabFocus:          'Focus',
      keyArtistsLabel:   'Key artists:',
      refugeTracksLabel: 'Refuge songs:',
      dominantTimeLabel: 'Dominant time:',
    },
    finalReport: {
      pageTitle: 'Your Life in Songs',
      printButton: 'Print / PDF',
      coverBadge: 'Nova Music Lab · Personal Report 2026',
      coverHeadlinePre: 'What ',
      coverHeadlineHighlight: '11 years of music',
      coverHeadlinePost: 'reveal about me',
      coverSubtitlePre: 'An essay for ',
      coverSubtitleName: 'Kevin Cusnir / Lirioth Teltanion',
      statScrobbles: 'Scrobbles',
      statHours: 'Hours',
      statArtists: 'Artists',
      statTracks: 'Tracks',
      s1Roman: 'I',
      s1Title: 'The Value of a Sonic Footprint',
      s1Pre: 'Kevin, the music we listen to is the seismic record of our inner world. Looking at your',
      s1Mid: 'logged since 2015, we are not reading statistics — we are reading an intimate emotional diary. Your',
      s1Post: 'speak of moves, nights of hyperfixation, and mornings of pure energy.',
      s1ScrobblesLabel: 'scrobbles',
      s1HoursLabel: 'hours listened',
      s1Quote: "Your music is not a playlist. It's the map of every world you've inhabited.",
      s2Roman: 'II',
      s2Title: 'The Eras: Chapters of a Life',
      s2Pre: 'In 2015,',
      s2ArtistName: 'Carpenter Brut',
      s2ArtistIntro: 'opened the first chapters. In 2018, your active streak of',
      s2StreakLabel: 'consecutive days',
      s2Mid: (peakLabel: string) => `reflects unprecedented life intensity. The ${peakLabel} arc is your musical peak with`,
      s2CombinedLabel: 'combined scrobbles',
      s2Quote: '"In Blur" is not just a song. It is the anthem of a version of you that learned to shine from the dark.',
      s3Roman: 'III',
      s3Title: 'The DNA: Who You Are According to Your Music',
      s3Pre: 'With',
      s3ArtistsLabel: 'unique artists',
      s3Mid: 'and',
      s3TracksLabel: 'unique tracks',
      s3ArchetypeIntro: 'you are a',
      s3Archetype: 'High-Intensity Explorer',
      s3NightIntro: 'Your',
      s3NightLabel: (nightRatio: number) => `${nightRatio}% night listening`,
      s3Post: 'reveals that music is also emotional regulation: silence inhabited by frequencies.',
      s3Quote: "You don't listen to background music. You listen as if every song deserved to be remembered.",
      s4Roman: 'IV',
      s4Title: 'Lirioth: The Creative Projection',
      s4Pre: 'Your alias',
      s4AliasLabel: 'Lirioth Teltanion',
      s4Post: 'is the synthesis of everything your music has built. The sound that defines you — post-hardcore guitars, cyberpunk synths and alternative groove — is an artistic proposal ready for music production, video games, digital art or storytelling.',
      s4Quote: 'Your next era will not be about consuming. It will be about creating.',
      s5Roman: 'V',
      s5Title: 'Keep Listening to Keep Becoming',
      s5Pre: 'Kevin, your story shows extraordinary emotional sensitivity and a resilience that knows how to resurface. Every one of your',
      s5DaysLabel: 'active days',
      s5Post: (topArtist: string, topTrack: string) => `is evidence that music has been language, therapy, identity and future all at once. ${topArtist} and "${topTrack}" will always be there.`,
      footerName: '✧ LIRIOTH TELTANION ✧',
      footerSubtitle: 'Nova Music Lab · Personal Museum · 2026',
    },
  },
} as const;

export type TranslationKeys = typeof STRINGS.es;

// ─── Themes ───────────────────────────────────────────────────────────────────
export const THEMES: Record<Theme, ThemeColors> = {
  cyber: {
    c1: '#00f2fe', c2: '#f72585', c3: '#7209b7', c4: '#4cc9f0',
    bg: '#050b14', name: 'cyber', label: '⚡ Cyber',
  },
  aurora: {
    c1: '#10b981', c2: '#34d399', c3: '#059669', c4: '#6ee7b7',
    bg: '#050f0a', name: 'aurora', label: '🌿 Aurora',
  },
  crimson: {
    c1: '#ef4444', c2: '#f97316', c3: '#b91c1c', c4: '#fb923c',
    bg: '#0f0505', name: 'crimson', label: '🔥 Crimson',
  },
  nebula: {
    c1: '#8b5cf6', c2: '#a78bfa', c3: '#7c3aed', c4: '#c4b5fd',
    bg: '#06050f', name: 'nebula', label: '🔮 Nebula',
  },
  ocean: {
    c1: '#06b6d4', c2: '#0284c7', c3: '#0e7490', c4: '#67e8f9',
    bg: '#03080f', name: 'ocean', label: '🌊 Ocean',
  },
  gold: {
    c1: '#f59e0b', c2: '#f97316', c3: '#d97706', c4: '#fcd34d',
    bg: '#0a0700', name: 'gold', label: '🌕 Gold',
  },
  midnight: {
    c1: '#60a5fa', c2: '#818cf8', c3: '#3b82f6', c4: '#93c5fd',
    bg: '#020509', name: 'midnight', label: '🌙 Midnight',
  },
};

function isLang(value: string | null): value is Lang {
  return value === 'es' || value === 'en';
}

function isTheme(value: string | null): value is Theme {
  return Boolean(value && value in THEMES);
}

// ─── Context ──────────────────────────────────────────────────────────────────
interface AppContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: TranslationKeys;
  theme: Theme;
  setTheme: (th: Theme) => void;
  tc: ThemeColors;
}

const AppContext = createContext<AppContextValue>({
  lang: 'es',
  setLang: () => {},
  t: STRINGS.es,
  theme: 'cyber',
  setTheme: () => {},
  tc: THEMES.cyber,
});

export function AppProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const stored = localStorage.getItem('nml_lang');
    return isLang(stored) ? stored : 'es';
  });
  const [theme, setThemeState] = useState<Theme>(() => {
    const stored = localStorage.getItem('nml_theme');
    return isTheme(stored) ? stored : 'cyber';
  });

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    localStorage.setItem('nml_lang', l);
  }, []);

  const setTheme = useCallback((th: Theme) => {
    setThemeState(th);
    localStorage.setItem('nml_theme', th);
  }, []);

  // Apply CSS variables to :root whenever theme changes
  useEffect(() => {
    const tc = THEMES[theme];
    const root = document.documentElement;
    root.setAttribute('data-theme', theme);
    root.style.setProperty('--c1', tc.c1);
    root.style.setProperty('--c2', tc.c2);
    root.style.setProperty('--c3', tc.c3);
    root.style.setProperty('--c4', tc.c4);
    root.style.setProperty('--bg', tc.bg);
  }, [theme]);

  return (
    <AppContext.Provider value={{
      lang, setLang,
      t: STRINGS[lang] as TranslationKeys,
      theme, setTheme,
      tc: THEMES[theme],
    }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  return useContext(AppContext);
}
